import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const timerSrc = await readFile(new URL("../src/sleepTimer.ts", import.meta.url), "utf8");
const app = await readFile(new URL("../src/App.tsx", import.meta.url), "utf8");
const css = await readFile(new URL("../src/styles.css", import.meta.url), "utf8");
const main = await readFile(new URL("../electron/main.cjs", import.meta.url), "utf8");

assert.doesNotMatch(app, /Live2DCharacter/);
assert.doesNotMatch(app, /sendInteraction/);
assert.match(app, /playSfx/);
assert.match(app, /className="overlay"/);
assert.match(app, /MahoPuppet/);
assert.match(app, /clip\.url/);
assert.match(app, /playSpeech/);
assert.match(app, /nextStep/);
assert.match(app, /if \(sleeping\) setCycle/);
const pointer = await readFile(new URL("../src/overlayPointer.ts", import.meta.url), "utf8");
assert.match(pointer, /DRAG_THRESHOLD_PX = 5/);
assert.match(pointer, /suppressClick/);
assert.match(pointer, /touch-point/);
assert.match(pointer, /cursor = pointingTarget/);
const hits = await readFile(new URL("../src/interactions.ts", import.meta.url), "utf8");
assert.match(hits, /label: "Cat"/);
assert.match(hits, /label: "Head"/);
assert.doesNotMatch(hits, /label: "Talk"/);
assert.doesNotMatch(hits, /talk\.wav/);
assert.match(hits, /\/maho\/clip39\.wav/);
assert.match(hits, /\/maho\/head10a\.wav/);
assert.match(hits, /\/maho\/head\.wav/);
assert.match(hits, /\/maho\/grr\.wav/);
assert.match(hits, /AnnoyedReaction/);
assert.match(hits, /sfx: true/);
assert.equal((hits.match(/sfx: true/g) ?? []).length, 3);
assert.match(hits, /top: "26%"/);
assert.doesNotMatch(hits, /backendId/);
assert.doesNotMatch(hits, /PatReaction/);
const speech = await readFile(new URL("../src/audio/SpeechPlayer.ts", import.meta.url), "utf8");
assert.match(speech, /isSpeaking\(\): boolean/);
assert.match(speech, /emitVisemes/);
assert.match(speech, /this.audio.volume = 1/);
const motionSrc = await readFile(new URL("../src/maho/motion.ts", import.meta.url), "utf8");
assert.doesNotMatch(motionSrc, /idle" \? "mouth-open"/);
const puppet = await readFile(new URL("../src/components/MahoPuppet.tsx", import.meta.url), "utf8");
assert.match(puppet, /new Audio\(url\)/);
assert.match(app, /ZzzLayer/);
assert.match(css, /\.touch-point/);
assert.match(css, /cursor: pointer/);
assert.match(app, /touch-point/);
assert.doesNotMatch(app, /disabled=\{busy\}/);
assert.match(css, /\.anger-mark/);
assert.match(css, /font-size: calc\(100vw \/ 56\)/);
assert.match(css, /width: 5\.8em/);
assert.match(css, /font-size: 3\.6em/);
assert.match(timerSrc, /IDLE_SLEEP_MS = 45_000/);
assert.match(css, /\.overlay\s*\{/);
assert.match(css, /\.zzz-layer/);
assert.match(main, /transparent:\s*true/);
assert.match(main, /hasShadow:\s*false/);
assert.match(main, /alwaysOnTop:\s*true/);
assert.doesNotMatch(main, /focusable:\s*false/);
assert.doesNotMatch(main, /release-focus/);
assert.doesNotMatch(pointer, /releaseFocus/);
assert.match(pointer, /keydown/);
assert.match(app, /tabIndex=\{-1\}/);
assert.match(app, /onMouseDown/);
assert.match(css, /box-shadow:\s*none/);
function sizeOf(id: string) {
  const match = main.match(new RegExp(`${id}: \\{ width: (\\d+), height: (\\d+) \\}`));
  assert.ok(match, id);
  return { width: Number(match[1]), height: Number(match[2]) };
}
const small = sizeOf("small");
const medium = sizeOf("medium");
const large = sizeOf("large");
const xl = sizeOf("xl");
assert.equal(large.width, 560);
assert.equal(large.height, 780);
assert.ok(small.width < medium.width && medium.width < large.width && large.width < xl.width);
assert.ok(small.height < medium.height && medium.height < large.height && large.height < xl.height);
assert.equal(small.width / small.height, large.width / large.height);
assert.equal(medium.width / medium.height, large.width / large.height);
assert.equal(xl.width / xl.height, large.width / large.height);
assert.match(main, /DEFAULT_SIZE = "large"/);
assert.match(main, /label: "Size"/);
assert.match(main, /small: "Small"/);
assert.match(main, /medium: "Medium"/);
assert.match(main, /large: "Large"/);
assert.match(main, /xl: "XL"/);
assert.match(main, /SIZE_LABELS\[id\]/);
assert.match(main, /type: "radio"/);
assert.match(main, /Quit Maho Overlay/);
assert.match(main, /setBounds/);
assert.doesNotMatch(main, /maho-small\.png/);
assert.match(main, /Maho Overlay/);

const rootReadme = await readFile(new URL("../../README.md", import.meta.url), "utf8");
assert.match(rootReadme, /# maho-overlay/);
assert.match(rootReadme, /start_local\.bat/);
assert.match(rootReadme, /py -3\.12/);
assert.match(rootReadme, /martialsystems\/maho-overlay/);
assert.doesNotMatch(rootReadme, /\u2014/);
assert.doesNotMatch(rootReadme, /What it is not/);
assert.match(rootReadme, /ko-fi\.com\/martialgames/);
assert.match(rootReadme, /Donate on Ko-fi/);
assert.match(rootReadme, /Click the cat/);
assert.doesNotMatch(rootReadme, /Talk:/);
assert.match(rootReadme, /Head:/);
assert.match(rootReadme, /clip 39/);
assert.match(rootReadme, /Sleep starts the loop over/);
assert.equal((rootReadme.match(/^- Drag:/gm) ?? []).length, 1);
assert.match(rootReadme, /Small, Medium, Large, XL/);
assert.match(rootReadme, /1264×1568 PNG/);

const winBat = await readFile(new URL("../../start_local.bat", import.meta.url), "utf8");
assert.match(winBat, /launcher\.py" --no-ai/);
assert.match(winBat, /backend\\\.venv\\Scripts\\python\.exe/);

const license = await readFile(new URL("../../LICENSE", import.meta.url), "utf8");
const notice = await readFile(new URL("../../NOTICE", import.meta.url), "utf8");
assert.match(license, /MIT License/);
assert.match(license, /Martial Systems LLC/);
assert.match(notice, /frontend\/public\/maho/);
assert.doesNotMatch(notice, /Live2D Cubism Core/);
